---
title: "Explore Landscape data"
author: "Anna Talucci"
date: "2023-04-21"
output: html_document
---

# Overview

# Packages

```{r}
library(tidyverse)
library(sf)
```
# Projections
```{r}
wgs_proj = "+proj=longlat +datum=WGS84 +no_defs"
```

```{r}
canada_proj = "+proj=aea +lat_0=40 +lon_0=-96 +lat_1=50 +lat_2=70 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs +type=crs"
```

# Data

## Landscape 1

```{r}
L1 = st_read("../data/FirstLandscape/caribou_pker_ck.shp", "caribou_pker_ck")
```
```{r}
st_crs(L1)$proj4string
L1_projection = st_crs(L1)$proj4string
st_crs(L1)$epsg
```

```{r}
st_area(L1)
```

## All landscapes

```{r}
LandLatLon = st_read("../data/Landscapes/final_plots_lat_lon.shp", "final_plots_lat_lon")
```

```{r}
LandLatLon
```
```{r}
Land = st_read("../data/Landscapes/final_plots.shp", "final_plots")
```

```{r}
Land
```
## State

```{r eval=FALSE, include=FALSE}
akState = st_read("../data/Boundaries/AlaskaState3338.shp", "AlaskaState3338")
```



```{r}
BiFires = st_read("../data/burnArea/LBaAk3338.shp", "LBaAk3338")
canFires = st_read("../data/burnArea/LBaCanf3005.shp", "LBaCanf3005")
```

# Select Landscapes for Alaska
```{r}
Land
unique(Land$ecoregion)
```

```{r}
( akLandscapes = LandLatLon %>% filter(ecoregion=="ALASKA BOREAL INTERIOR"))
```

# Reproject
```{r}
ak_landscapes = st_transform(akLandscapes, crs = 3338)
```




# Map
```{r}
ggplot() +
  geom_sf(data = LandLatLon, fill=NA, color = "blue") +
    coord_sf()
```

```{r}
ggplot() +
  geom_sf(data = Land, fill=NA, color = "blue") +
    coord_sf()
```


```{r}
ggplot() +
  geom_sf(data = canFires, fill=NA, color = "orange") +
  geom_sf(data = Land, fill=NA, color = "blue") +
    coord_sf()
```

