---
title: "Organize shapefile data"
author: "Anna Talucci"
date: "2023-06-08"
output: html_document
---

# Overview

Pull out AK fire perimeters from full USA data set

Combines Canadian Fires into single shape file

Adds eco property to landscapes

# Packages
```{r}
library(terra)
library(gdalUtilities)
library(sf)
library(tidyverse)
```

# Data
## State
	
```{r}
st = st_read("../data/alaska/GU_StateOrTerritory.shp", "GU_StateOrTerritory") 
```

## Landscapes
```{r}
landscapes = st_read("../data/Landscapes/final_plots_lat_lon.shp", "final_plots_lat_lon")
```

## USA Fire perimeters
```{r}
usa = st_read("../data/mtbs_perimeter_data/mtbs_perims_DD.shp", "mtbs_perims_DD")
```
## Canadian Fires
```{r}
CanFires = st_read("../data/nbac_1986_to_2020/nbac_1986_to_2020_20210810.shp", "nbac_1986_to_2020_20210810")
CanFires2021 = st_read("../data/nbac_2021/nbac_2021_r9_20220624.shp", "nbac_2021_r9_20220624")
```

# Select Alaska Fires
```{r}
( akFires = usa %>% filter(BurnBndLat > 50) )
```

# Combine Canadian Fires
```{r}
( CanFires = CanFires %>% dplyr::select(-BASRC_1, -new_flg) %>%
    bind_rows(., CanFires2021) %>%
    dplyr::select(-COMMENTS))
```


#  Alaska Boundary 
 
```{r}
(akState = st %>% filter(NAME_En == "Alaska") )
```


# Add property to landscapes

```{r}
landscapes = landscapes %>% 
  mutate(eco = ifelse(ecoregion == "ALASKA BOREAL INTERIOR", "BI",
                                     ifelse(ecoregion == "BOREAL CORDILLERA", "BC",
                                            ifelse(ecoregion == "TAIGA PLAIN", "TP",
                                                   ifelse(ecoregion == "TAIGA SHIELD", "TS", "NA"))))) %>%
  mutate(epsg = ifelse(ecoregion == "ALASKA BOREAL INTERIOR", 3338,
                                     ifelse(ecoregion == "BOREAL CORDILLERA", 3005,
                                            ifelse(ecoregion == "TAIGA PLAIN", 3005,
                                                   ifelse(ecoregion == "TAIGA SHIELD", 3005, "NA"))))) 
  
```

```{r}
landscapes
```

# Reproject

```{r}
akFires = st_transform(akFires, crs = 3338)
akState = st_transform(akState, crs = 3338)
CanFires = st_transform(CanFires, crs = 3005)
```

# Write to file
```{r eval=FALSE, include=FALSE}
st_write(ak_st, "../outputs/shp/AlaskaState3338.shp", driver="ESRI Shapefile")
```

```{r eval=FALSE, include=FALSE}
st_write(akFires, "../outputs/perimeters/AlaskaFires3338.shp", driver="ESRI Shapefile")
```

```{r eval=FALSE, include=FALSE}
st_write(CanFires, "../outputs/perimeters/CanadaFires3005.shp", driver="ESRI Shapefile")
```

```{r eval=FALSE, include=FALSE}
st_write(landscapes, "../outputs/landscapes/finalPlotsWGS84.shp", driver="ESRI Shapefile")
```